name: Run Crypto News Bot

on:
  workflow_dispatch:  # Allow manual execution
  # Uncomment to run on schedule
  # schedule:
  #   - cron: "0 * * * *"  # Run every hour

jobs:
  run_script:
    runs-on: ubuntu-22.04

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # Step 3: Install Chrome and ChromeDriver
      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get -f install -y
          wget https://chromedriver.storage.googleapis.com/$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      # Step 4: Install required Python libraries
      - name: Install dependencies
        run: |
          pip install requests selenium webdriver-manager

      # Step 5: Export environment variables
      - name: Set environment variables for the script
        env:
          CRYPTOPANIC_API_KEY: ${{ secrets.CRYPTOPANIC_API_KEY }}
          EASY_PEASY_API_KEY: ${{ secrets.EASY_PEASY_API_KEY }}
        run: echo "Environment variables set."

      # Step 6: Download the cookies file (if it exists)
      - name: Download cookies
        uses: actions/download-artifact@v3
        with:
          name: cookies
          path: cookies.pkl
        continue-on-error: true  # Proceed even if the cookies file doesn't exist

      # Step 7: Run the Python script
      - name: Run Python script
        env:
          CRYPTOPANIC_API_KEY: ${{ secrets.CRYPTOPANIC_API_KEY }}
          EASY_PEASY_API_KEY: ${{ secrets.EASY_PEASY_API_KEY }}
        run: python cryptonews_translator.py

      # Step 8: Upload cookies file (after login)
      - name: Upload cookies
        if: always()  # Ensure cookies are uploaded even if the script fails
        uses: actions/upload-artifact@v3
        with:
          name: cookies
          path: cookies.pkl
